services:
  backend:
    environment:
      DEV_MODE: "true"
    entrypoint: [ "tail", "-f", "/dev/null" ]

  frontend:
    environment:
      DEV_MODE: "true"
    entrypoint: [ "tail", "-f", "/dev/null" ]
